### ISSUE TITLE
Update browserslist regularly

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/platform-plugin-dev-docker#8]
### Please describe the feature you would like to see implemented.

We should update browserslist database in storefront and administration regularly:
```
[info] [webpackbar] Compiling Shopware 6 Storefront
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```

**Comment by shyim** [comment]
I guess its a core issue and not for this project

**Comment by tinect** [comment]
This ticket is not an issue, just a enhancement :-) 
Because we can deal it foe plugins this way.
